# Generated by Django 5.2.16 on 2026-09-01 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sql', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DdlSyncPair',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="DBA 自己起, 如 'accesscard 库对'", max_length=128, verbose_name='配对名')),
                ('source_db', models.CharField(max_length=64, verbose_name='业务库名')),
                ('target_db', models.CharField(max_length=64, verbose_name='历史库名')),
                ('sync_mode', models.CharField(choices=[('blacklist', '黑名单 (默认, 业务库全同步, 显式排除)'), ('whitelist', '白名单 (DBA 显式选要同步的)')], default='blacklist', help_text='R1 改默认 blacklist (业务库 1589 张表全要同步, DBA 显式排除更省事)', max_length=16, verbose_name='同步模式')),
                ('enabled', models.BooleanField(default=True, help_text='软删, 禁用不影响历史数据', verbose_name='启用')),
                ('pending_tables', models.JSONField(blank=True, default=dict, help_text="R3 Phase 2 用, 业务库新增表自动入'待确认', DBA 1-click 加白/黑名单", verbose_name='待确认表')),
                ('filter_rule', models.JSONField(blank=True, default=dict, help_text='R3 Phase 3 用, 排除前缀/后缀/ENGINE/空表/最小大小', verbose_name='过滤规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_ddl_sync_pair', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('source_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_pair_source', to='sql.instance', verbose_name='业务库实例')),
                ('target_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_pair_target', to='sql.instance', verbose_name='历史库实例')),
            ],
            options={
                'verbose_name': 'DDL 跨库同步库对',
                'verbose_name_plural': 'DDL 跨库同步库对',
                'db_table': 'ext_ddl_sync_pair',
                'unique_together': {('source_instance', 'source_db')},
            },
        ),
        migrations.CreateModel(
            name='DdlSyncHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=128, verbose_name='同步表名')),
                ('ddl_text', models.TextField(help_text='业务库工单原始 SQL', verbose_name='原始 DDL')),
                ('transformed_ddl_text', models.TextField(blank=True, default='', help_text='应用 transform_rule 后的 DDL, 历史库实际执行的 SQL', verbose_name='转换后 DDL')),
                ('sync_status', models.CharField(choices=[('pending', '待执行 (业务库 DDL 已过审, 镜像工单待生成)'), ('syncing', '同步中 (镜像工单已生成, 还没执行)'), ('synced', '同步成功 (历史库镜像工单执行成功)'), ('skipped', '跳过 (白名单不含/黑名单含, 不生成镜像工单)'), ('failed', '失败 (历史库镜像工单执行失败)')], db_index=True, default='pending', max_length=16, verbose_name='同步状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='失败信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('source_workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_source', to='sql.sqlworkflow', verbose_name='业务库工单')),
                ('target_workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_target', to='sql.sqlworkflow', verbose_name='历史库镜像工单')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ddl_sync.ddlsyncpair', verbose_name='库对')),
            ],
            options={
                'verbose_name': 'DDL 跨库同步历史',
                'verbose_name_plural': 'DDL 跨库同步历史',
                'db_table': 'ext_ddl_sync_history',
                'indexes': [models.Index(fields=['sync_status', '-created_at'], name='ext_ddl_syn_sync_st_0e75dd_idx'), models.Index(fields=['pair', '-created_at'], name='ext_ddl_syn_pair_id_53876c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DdlSyncTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('table_name', models.CharField(help_text="业务库表名 (不带 schema, 如 'accesscard_black_detail')", max_length=128, verbose_name='表名')),
                ('sync_type', models.CharField(choices=[('whitelist', '白名单 (要同步)'), ('blacklist', '黑名单 (不同步)')], default='whitelist', help_text='区分白/黑名单 (跟 pair.sync_mode 配合, R2 加)', max_length=16, verbose_name='同步类型')),
                ('transform_rule', models.JSONField(blank=True, default=dict, help_text='Phase 3 用, 跳过列/重命名列/字段类型转换', verbose_name='字段级调整规则')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='ddl_sync.ddlsyncpair', verbose_name='库对')),
            ],
            options={
                'verbose_name': 'DDL 跨库同步表',
                'verbose_name_plural': 'DDL 跨库同步表',
                'db_table': 'ext_ddl_sync_table',
                'indexes': [models.Index(fields=['pair', 'table_name'], name='ext_ddl_syn_pair_id_173580_idx')],
                'unique_together': {('pair', 'table_name', 'sync_type')},
            },
        ),
    ]
