# Generated by Django 5.2.16 on 2026-09-03 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddl_sync', '0001_initial'),
        ('sql', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddlsyncpair',
            name='target_group',
            field=models.ForeignKey(blank=True, help_text='DBA 配库对时显式选 (Instance 是 M2M ResourceGroup, 不能自动猜); 走当前 group_id 的 WorkflowAuditSetting (SQL_REVIEW) 拿审流', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sync_pair_target_group', to='sql.resourcegroup', verbose_name='镜像工单审批组'),
        ),
        migrations.AddField(
            model_name='ddlsyncpair',
            name='target_group_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='镜像工单审批组名'),
        ),
    ]
