# Generated by Django 5.2.16 on 2026-09-09 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddl_sync", "0002_ddlsyncpair_target_group_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DdlSyncAuditLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建库对"),
                            ("edit", "编辑库对 (非启用/禁用字段)"),
                            ("enable", "启用库对"),
                            ("disable", "禁用库对"),
                            ("one_click", "一键配置 (R2)"),
                            ("bulk_import", "批量导入 (R1)"),
                        ],
                        db_index=True,
                        max_length=16,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "operator_display",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="冗余 operator 的 username, 用户被删后仍能展示",
                        max_length=64,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "detail_json",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="按 action 类型不同 schema 不同, 见模型 docstring",
                        verbose_name="详情 JSON",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="操作时间"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ddl_sync_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
                (
                    "pair",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_logs",
                        to="ddl_sync.ddlsyncpair",
                        verbose_name="库对",
                    ),
                ),
            ],
            options={
                "verbose_name": "DDL 跨库同步操作日志",
                "verbose_name_plural": "DDL 跨库同步操作日志",
                "db_table": "ext_ddl_sync_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["pair", "-created_at"],
                        name="ext_ddl_syn_pair_id_ac16bc_idx",
                    ),
                    models.Index(
                        fields=["pair", "action", "-created_at"],
                        name="ext_ddl_syn_pair_id_4d389f_idx",
                    ),
                ],
            },
        ),
    ]
