# Generated by Django 5.2.16 on 2026-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddl_sync", "0003_ddlsyncauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="ddlsyncauditlog",
            name="client_ip",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="从 X-Forwarded-For (有反代时) 或 REMOTE_ADDR 拿",
                null=True,
                verbose_name="客户端 IP",
            ),
        ),
        migrations.AddField(
            model_name="ddlsyncauditlog",
            name="is_backfilled",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True=脚本从 Archery LogEntry 补录, False=DBA 真实操作",
                verbose_name="补录数据",
            ),
        ),
        migrations.AddField(
            model_name="ddlsyncauditlog",
            name="user_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HTTP_USER_AGENT, 截断 256 字符",
                max_length=256,
                verbose_name="浏览器 UA",
            ),
        ),
        migrations.AlterField(
            model_name="ddlsyncauditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "创建库对"),
                    ("edit", "编辑库对 (非启用/禁用字段)"),
                    ("enable", "启用库对"),
                    ("disable", "禁用库对"),
                    ("one_click", "一键配置 (R2)"),
                    ("bulk_import", "批量导入 (R1)"),
                    ("add_table", "新增同步表"),
                    ("delete_table", "删除同步表"),
                    ("transform_change", "改 transform_rule"),
                ],
                db_index=True,
                max_length=16,
                verbose_name="操作类型",
            ),
        ),
    ]
