# Generated by Django 5.2.16 on 2026-07-21 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sql', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('code', models.CharField(help_text='如 normal / critical / self_service / default', max_length=32, primary_key=True, serialize=False, verbose_name='流程编码')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('audit_driver', models.CharField(choices=[('archery', 'Archery 本地 Group 审批'), ('dingtalk_oa', '钉钉 OA 智能工作流')], max_length=32, verbose_name='审批驱动')),
                ('audit_auth_groups', models.CharField(help_text='逗号分隔的 Group ID 列表，按审批顺序', max_length=500, verbose_name='审批权限组列表')),
                ('dingtalk_process_code', models.CharField(blank=True, help_text='仅 audit_driver=dingtalk_oa 时填', max_length=64, verbose_name='钉钉 OA 模板编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审批流程',
                'verbose_name_plural': '审批流程',
                'db_table': 'ext_approval_flow',
            },
        ),
        migrations.CreateModel(
            name='SqlTypeRegistry',
            fields=[
                ('code', models.CharField(help_text='主键，如 INSERT/DROP/TRUNCATE ...', max_length=32, primary_key=True, serialize=False, verbose_name='类型编码')),
                ('category', models.CharField(help_text='DML / DDL / DQL / DCL', max_length=16, verbose_name='分类')),
                ('description', models.CharField(max_length=128, verbose_name='说明')),
                ('pattern', models.CharField(help_text='用于从 SQL 文本中匹配本类型，区分大小写由调用方控制', max_length=255, verbose_name='识别正则')),
                ('default_severity', models.CharField(help_text='low / medium / high', max_length=16, verbose_name='默认风险等级')),
                ('has_affected_rows', models.BooleanField(default=True, help_text='DDL/DQL 类设为 False，不参与行数维度判定', verbose_name='是否参与行数维度')),
                ('is_critical', models.BooleanField(default=False, help_text='高危类型：DROP/TRUNCATE 等', verbose_name='是否高危')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'SQL 类型注册表',
                'verbose_name_plural': 'SQL 类型注册表',
                'db_table': 'ext_sql_type_registry',
            },
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('priority', models.IntegerField(default=0, help_text='数字越大优先级越高；按 priority 倒序遍历匹配', verbose_name='优先级')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('sql_type_match_mode', models.CharField(choices=[('any', '任一命中'), ('all', '全部命中')], default='any', max_length=16, verbose_name='SQL 类型匹配方式')),
                ('require_core_table', models.BooleanField(default=False, help_text='True 时，工单涉及表必须在 CoreBusinessTable 中', verbose_name='要求命中核心业务表')),
                ('table_levels', models.CharField(blank=True, help_text='L1,L2 多个用逗号分隔；空表示任意等级', max_length=16, verbose_name='核心表等级')),
                ('min_affected_rows', models.IntegerField(blank=True, null=True, verbose_name='最小影响行数')),
                ('max_affected_rows', models.IntegerField(blank=True, null=True, verbose_name='最大影响行数')),
                ('affected_rows_aggregate', models.CharField(choices=[('total', '所有 SQL 总和'), ('max', '单条 SQL 最大值')], default='total', max_length=16, verbose_name='行数聚合方式')),
                ('legacy_syntax_types', models.CharField(blank=True, help_text='逗号分隔：0/1=DDL/2=DML/3=导出；可留空', max_length=32, verbose_name='兼容 syntax_type')),
                ('severity', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险')], default='medium', max_length=16, verbose_name='风险等级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('flow', models.ForeignKey(help_text='命中后跳转到哪个流程（PROTECT 防止误删）', on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='dingtalk_oa.approvalflow')),
                ('sql_types', models.ManyToManyField(blank=True, help_text='命中 SQL 类型集合', related_name='policies', to='dingtalk_oa.sqltyperegistry')),
            ],
            options={
                'verbose_name': '审批策略',
                'verbose_name_plural': '审批策略',
                'db_table': 'ext_approval_policy',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditExternal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(help_text='如 dingtalk_oa；留作未来扩展', max_length=32, verbose_name='来源')),
                ('external_process_instance_id', models.CharField(db_index=True, max_length=128, verbose_name='外部流程实例 ID')),
                ('external_process_code', models.CharField(max_length=64, verbose_name='外部流程模板编码')),
                ('current_external_node', models.CharField(blank=True, max_length=64, verbose_name='当前外部节点')),
                ('external_status', models.CharField(help_text='RUNNING / APPROVED / REJECTED / TERMINATED / FALLBACK', max_length=32, verbose_name='外部流程状态')),
                ('oa_failure_reason', models.CharField(blank=True, help_text='降级时填写，便于排查', max_length=500, verbose_name='OA 失败原因')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='最近同步时间')),
                ('fallback_at', models.DateTimeField(blank=True, null=True, verbose_name='降级时间')),
                ('reconcile_failed_count', models.IntegerField(default=0, verbose_name='对账失败次数')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='外部 OA 透传快照')),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='external_audit', to='sql.workflowaudit')),
            ],
            options={
                'verbose_name': '工单外部 OA 关联',
                'verbose_name_plural': '工单外部 OA 关联',
                'db_table': 'ext_workflow_audit_external',
            },
        ),
        migrations.CreateModel(
            name='CoreBusinessTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('db_name', models.CharField(max_length=64, verbose_name='数据库名')),
                ('table_name', models.CharField(max_length=128, verbose_name='表名')),
                ('level', models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=8, verbose_name='等级')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sql.instance', verbose_name='所属实例')),
            ],
            options={
                'verbose_name': '核心业务表',
                'verbose_name_plural': '核心业务表',
                'db_table': 'ext_core_business_table',
                'indexes': [models.Index(fields=['db_name', 'table_name'], name='ext_core_bu_db_name_c30f2c_idx')],
                'unique_together': {('instance', 'db_name', 'table_name')},
            },
        ),
        migrations.CreateModel(
            name='DingtalkOaEventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=32, verbose_name='事件类型')),
                ('event_id', models.CharField(db_index=True, max_length=64, verbose_name='事件 ID（幂等用）')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='事件内容')),
                ('signature', models.CharField(blank=True, max_length=128, verbose_name='签名')),
                ('raw_payload_encrypted', models.TextField(blank=True, verbose_name='原始密文（截断留存）')),
                ('processed', models.BooleanField(default=False, verbose_name='已处理')),
                ('error', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('audit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dingtalk_events', to='sql.workflowaudit')),
            ],
            options={
                'verbose_name': '钉钉 OA 事件流水',
                'verbose_name_plural': '钉钉 OA 事件流水',
                'db_table': 'ext_dingtalk_oa_event_log',
                'indexes': [models.Index(fields=['created_at'], name='ext_dingtal_created_d213ee_idx'), models.Index(fields=['audit', 'event_type'], name='ext_dingtal_audit_i_b26611_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupDingtalkAuditor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dingtalk_user_ids', models.TextField(blank=True, help_text="JSON 数组，如 ['user1','user2']", verbose_name='钉钉用户 ID 列表')),
                ('dingtalk_dept_id', models.CharField(blank=True, max_length=64, verbose_name='钉钉部门 ID')),
                ('dingtalk_cc_user_ids', models.TextField(blank=True, help_text='JSON 数组', verbose_name='钉钉抄送用户 ID 列表')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_auditors', to='auth.group')),
                ('resource_group', models.ForeignKey(blank=True, help_text='为空表示跨资源组通用', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dingtalk_auditors', to='sql.resourcegroup')),
            ],
            options={
                'verbose_name': '审批人钉钉映射',
                'verbose_name_plural': '审批人钉钉映射',
                'db_table': 'ext_group_dingtalk_auditor',
                'unique_together': {('group', 'resource_group')},
            },
        ),
    ]
