# Generated by Django 5.2.16 on 2026-08-06 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sql", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="DdlGhostTask",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="用户勾选 = 走 gh-ost；未勾选 = 走传统 ALTER，task 不创建",
                        verbose_name="启用 gh-ost",
                    ),
                ),
                (
                    "cut_over_strategy",
                    models.CharField(
                        choices=[
                            ("immediate", "立即切（默认，alpha 阶段）"),
                            ("low_traffic_window", "业务低峰期切（02:00-04:00）"),
                            ("manual", "DBA 手动触发"),
                        ],
                        default="immediate",
                        max_length=32,
                        verbose_name="切表策略",
                    ),
                ),
                (
                    "cut_over_window_start",
                    models.TimeField(blank=True, null=True, verbose_name="低峰期起始"),
                ),
                (
                    "cut_over_window_end",
                    models.TimeField(blank=True, null=True, verbose_name="低峰期结束"),
                ),
                (
                    "max_load_threads_running",
                    models.IntegerField(
                        default=30,
                        help_text="超过此值自动暂停 gh-ost 复制（生产保护）",
                        verbose_name="暂停阈值（threads_running）",
                    ),
                ),
                (
                    "timeout_seconds",
                    models.IntegerField(
                        default=7200,
                        help_text="超过此时间未完成自动停止，默认 2h",
                        verbose_name="超时熔断（秒）",
                    ),
                ),
                (
                    "precheck_passed",
                    models.BooleanField(default=False, verbose_name="预检通过"),
                ),
                (
                    "precheck_report",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="5 道检查每道的 status/evidence/message",
                        verbose_name="预检报告",
                    ),
                ),
                (
                    "precheck_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="预检时间"
                    ),
                ),
                (
                    "alter_statement",
                    models.TextField(
                        help_text="从 sql_content 提取的第一条 ALTER TABLE 语句",
                        verbose_name="ALTER 语句",
                    ),
                ),
                (
                    "db_name",
                    models.CharField(blank=True, max_length=64, verbose_name="数据库"),
                ),
                (
                    "table_name",
                    models.CharField(blank=True, max_length=128, verbose_name="原表名"),
                ),
                (
                    "ghost_table_name",
                    models.CharField(
                        blank=True,
                        help_text="gh-ost 生成，格式 _<table>_gho",
                        max_length=128,
                        verbose_name="影子表名",
                    ),
                ),
                (
                    "original_table_size_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="原表大小（字节）"
                    ),
                ),
                (
                    "disk_free_bytes",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="磁盘剩余（字节，预检时）"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待预检"),
                            ("precheck_failed", "预检未通过"),
                            ("queued", "排队中"),
                            ("running", "执行中"),
                            ("cut_over", "切表阶段"),
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("connecting", "connecting"),
                            ("copying", "Copying rows"),
                            ("waiting_cut_over", "waiting for cut-over"),
                            ("cut_over", "cut-over"),
                            ("swapped", "swapped"),
                            ("done", "done"),
                        ],
                        max_length=32,
                        verbose_name="gh-ost 阶段",
                    ),
                ),
                (
                    "ghost_pid",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="gh-ost PID"
                    ),
                ),
                (
                    "systemd_scope_unit",
                    models.CharField(
                        blank=True,
                        help_text="systemd-run --scope=ghost-<audit_id> 创建的临时 unit",
                        max_length=128,
                        verbose_name="systemd scope 单元",
                    ),
                ),
                (
                    "progress_pct",
                    models.IntegerField(default=0, verbose_name="进度百分比"),
                ),
                (
                    "progress_rows_copied",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="已复制行数"
                    ),
                ),
                (
                    "progress_rows_total",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="总行数"
                    ),
                ),
                (
                    "progress_speed_rows_per_sec",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="复制速度（行/s）"
                    ),
                ),
                (
                    "progress_eta_seconds",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="预计剩余（秒）"
                    ),
                ),
                (
                    "progress_threads_running",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="当前 threads_running"
                    ),
                ),
                (
                    "progress_message",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="最后一行 stdout 摘要"
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后心跳"
                    ),
                ),
                (
                    "stderr_tail",
                    models.TextField(
                        blank=True, verbose_name="stderr 末尾（最多 50 行）"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(blank=True, max_length=50, verbose_name="创建人"),
                ),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ghost_tasks",
                        to="sql.workflowaudit",
                        verbose_name="审批工单（审批通过后才有）",
                    ),
                ),
                (
                    "workflow",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghost_task",
                        to="sql.sqlworkflow",
                        verbose_name="SQL 工单",
                    ),
                ),
            ],
            options={
                "verbose_name": "gh-ost 任务",
                "verbose_name_plural": "gh-ost 任务",
                "db_table": "ext_ddl_ghost_task",
                "indexes": [
                    models.Index(
                        fields=["status"], name="ext_ddl_gho_status_598b5a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ext_ddl_gho_created_a61efa_idx"
                    ),
                ],
            },
        ),
    ]
