# Generated by Django 5.2.16 on 2026-08-06 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddl_gh_ost", "0001_initial"),
        ("sql", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="ddlghosttask",
            name="related_task_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="归档联动时存 ArchiveConfig.id；rebuild 内部队列存前序 task id",
                null=True,
                verbose_name="关联 task id",
            ),
        ),
        migrations.AddField(
            model_name="ddlghosttask",
            name="target_table",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="rebuild 场景存 db.table（如 archery_dev.accesscard_black_detail）；ghost 场景为空",
                max_length=128,
                verbose_name="目标表（rebuild 用）",
            ),
        ),
        migrations.AddField(
            model_name="ddlghosttask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("ghost", "gh-ost DDL（v0.3.0 改造，SQL 工单触发）"),
                    ("rebuild", "碎片回收（v0.4.5 改造，DBA 手动选表触发）"),
                ],
                db_index=True,
                default="ghost",
                help_text="ghost=gh-ost DDL 工单；rebuild=碎片回收（表级）",
                max_length=16,
                verbose_name="任务类型",
            ),
        ),
        migrations.AlterField(
            model_name="ddlghosttask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待预检"),
                    ("precheck_failed", "预检未通过"),
                    ("queued", "排队中"),
                    ("running", "执行中"),
                    ("cut_over", "切表阶段"),
                    ("success", "成功"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                    ("rolled_back", "已回滚"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="ddlghosttask",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ghost_task",
                to="sql.sqlworkflow",
                verbose_name="SQL 工单（rebuild 场景为 NULL）",
            ),
        ),
        migrations.AddConstraint(
            model_name="ddlghosttask",
            constraint=models.UniqueConstraint(
                fields=("task_type", "workflow"), name="uniq_task_type_workflow"
            ),
        ),
    ]
