# Generated by Django 5.2.16 on 2026-08-10 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddl_gh_ost", "0002_ddlghosttask_related_task_id_and_more"),
        ("sql", "__first__"),
    ]

    operations = [
        migrations.AddField(
            model_name="ddlghosttask",
            name="instance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ghost_tasks",
                to="sql.instance",
                verbose_name="实例（rebuild 必填）",
            ),
        ),
    ]
